### ISSUE TITLE
Changing environment launcher

### ISSUE THREAD

**Issue by bhairavmehta95** [duckietown/challenge-aido1_LF1-baseline-IL-sim-tensorflow#2]
https://github.com/duckietown/challenge-aido1_LF1-baseline-IL-sim-tensorflow/blob/d743f7217a4f2f3beea8e814f1a13c12cf6d8e94/eval.py#L14

We need to change the evaluation environment to be the one from here:
https://github.com/duckietown/challenge-aido1_LF1-baseline-RL-sim-pytorch/blob/master/duckietown_rl/env.py

**Comment by liampaull** [comment]
does this explain the confusion from the other day @takeitallsource @AndreaCensi ?

**Comment by lightaime** [comment]
Where is train.log file?
