### ISSUE TITLE
Bug- setup.py not found

### ISSUE THREAD

**Issue by rizavelioglu** [duckietown/challenge-aido1_LF1-baseline-IL-sim-tensorflow#6]
There's no file 'setup.py' in repo. Error can be reproduced by following the [Quickstart](http://docs.duckietown.org/DT19/AIDO/out/embodied_il_sim.html):

**1-** Clone repo: 
`$ git clone git@github.com:duckietown/challenge-aido_LF-baseline-IL-sim-tensorflow.git`
**2-** Change into the directory:  
`$ cd challenge-aido_LF-baseline-IL-sim-tensorflow`
**3-** Install this package:
`$ pip3 install -e .`

**ERROR: File "setup.py" not found. Directory cannot be installed in editable mode:**

**Comment by liampaull** [comment]
you have to go into the "learning" directory. Thanks for reporting. I updated the quickstart.

**Comment by rizavelioglu** [comment]
But in the "learning" directory, there's no setup.py file either

**Comment by liampaull** [comment]
sorry - should be `pip3 install -r requirements.txt`
